DECLARE 
	id

EMPLOYEES.EMPLOYEE_ID%type;
	BEGIN
		INSERT INTO EMPLOYEES(LAST_NAME,FIRST_NAME)
		VALUES(:LAST_NAME,:FIRST:NAME)
		RETURNING EMPLOYEE_ID INTO ID;
		:status :201;
		END;
		
		then JSON format using key/values pairs
		
		{"LAST_NAME":"SAWANT",
		"FIRST_NAME":"PALLAVI"}
		
		BEGIN
		DETETE FROM EMPLOYEES WHERE LAST_NAME="SAWANT"
		:staus :=204
		END;
